BEGIN;
-- AlterTable
ALTER TABLE "ActuaryContact" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "titleRole" DROP NOT NULL,
ALTER COLUMN "email" DROP NOT NULL,
ALTER COLUMN "actuarialFirm" DROP NOT NULL;

-- AlterTable
ALTER TABLE "StateContact" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "titleRole" DROP NOT NULL,
ALTER COLUMN "email" DROP NOT NULL;
COMMIT;
