query SyntheticFetchContract($input: FetchContractInput!) {
    fetchContract(input: $input) {
        contract {
            id
            stateCode
            status
            initiallySubmittedAt
            draftRevision {
                id
            }
            packageSubmissions {
                submitInfo {
                    updatedReason
                    updatedBy {
                        role
                        email
                    }
                }
                contractRevision {
                    unlockInfo {
                        updatedReason
                        updatedBy {
                            role
                            email
                        }
                    }
                    formData {
                        submissionDescription
                        modifiedBenefitsProvided
                        modifiedGeoAreaServed
                        contractDocuments {
                            name
                            s3URL
                            sha256
                            dateAdded
                        }
                        supportingDocuments {
                            name
                            s3URL
                            sha256
                            dateAdded
                        }
                    }
                }
                rateRevisions {
                    rateID
                    rate {
                        id
                        parentContractID
                        status
                    }
                    formData {
                        rateCertificationName
                        rateDocuments {
                            name
                            s3URL
                            sha256
                            dateAdded
                        }
                    }
                }
            }
        }
    }
}
