export type { S3ClientT } from './s3Client'
export type { S3Error } from './s3Error'
export { isS3Error } from './s3Error'
export type { BucketShortName, S3BucketConfigType } from './helpers'
export { parseBucketName, parseKey, getS3Bucket, getS3Key } from './helpers'
export { newLocalS3Client } from './s3Local'
export { newDeployedS3Client } from './s3Deployed'
