query FetchRevisionDiff($input: FetchRevisionDiffInput!) {
  fetchRevisionDiff(input: $input) {
    contractID
    comparison {
      olderRevisionID
      newerRevisionID
      olderSubmittedAt
      newerSubmittedAt
      fieldChanges {
        fieldPath
        oldValue {
          kind
          value
        }
        newValue {
          kind
          value
        }
      }
      stateContactChanges {
        kind
        current {
          name
          titleRole
          email
        }
      }
      documentChanges {
        contractDocuments {
          added
          removed
        }
        contractSupportingDocuments {
          added
          removed
        }
        rates {
          rateID
          rateCertificationName
          rateDocuments {
            added
            removed
          }
          supportingDocuments {
            added
            removed
          }
        }
        totalAdded
        totalRemoved
      }
    }
  }
}
