#!/bin/bash
. "$(dirname "$0")/_/husky.sh"

# In a continuing effort to print errors when they are needed, we check for
# all pre-commit dependency requirements here.
requirements=("protolint" "shellcheck" "detect-secrets")

for req in "${requirements[@]}"; do
    if ! command -v "$req" &> /dev/null; then
        echo "$req is required to run pre-commit. Check the README for installation instructions"
    fi
done

# Detect secrets in commit, excluding pnpm-lock.yaml
git diff --staged --name-only -z | grep -zv 'pnpm-lock.yaml' | xargs -0 detect-secrets-hook

# Run "precommit" in all pnpm workspaces 
echo "Pre-commit hook is running"
pnpm lint-staged --allow-empty
